enum Category {
    SOFTWARE, HARDWARE, NETWORKING
}

class Employee{
    String fullName;
    int pointLevel;
    Category assignedCategory;
        private Employee.Ticket[] tickets;
    }
    public Employee( String fullName, int pointLevel,Category assignedCategory){
        this.fullName=fullName;
        this.pointLevel=pointLevel;
        this.assignedCategory=assignedCategory;
    }
    public void showDetails(){
        System.out.println("employee name"+fullName);
        System.out.println("level"+pointLevel);
        System.out.println("Category"+assignedCategory);
    }
    class Ticket{
        int id;
        String name;
        Category category;
        int point;
        String assignedEmployee;
        boolean isCompleted;
    
    public Ticket(int id,String name,Category category,int point,String assignedEmployee,boolean isCompleted){
         this.id=id;
         this.name=name;
         this.category=category;
         this.point=point;
         this.assignedEmployee=assignedEmployee;
         this.isCompleted=isCompleted;
    }
    }
    class HelpDesk{
        private Employee emp1,emp2;
        private Ticket t1,t2,t3,t4,t5;
            private Employee.Ticket[] tickets;
                    private Object ticket;
                public HelpDesk(Employee emp1,Employee emp2,Ticket t1,Ticket t2, Ticket t3,Ticket t4,Ticket t5){
                    this.emp1=emp1;
                    this.emp2=emp2;
                    this.t1=t1;
                    this.t2=t2;
                    this.t3=t3;
                    this.t4=t4;
                    this.t5=t5;
                }
                public HelpDesk() {
                                    //TODO Auto-generated constructor stub
                                }
                                int getWaitingTicketCount(){
                                    int count=0;
                                    for (Ticket tickte:tickets){
                                    if(ticket!=null&&!ticket.isCompleted){
                                        count++;
                                    }
                        }
                        return count;
                    
                        }
                                        public void addEmployee(Employee alice, int i) {
                                            
                                            throw new UnsupportedOperationException("Unimplemented method 'addEmployee'");
                                        }
                                                                public void addTicket(Employee.Ticket t12, int i) {
                                                                   
                                                                    throw new UnsupportedOperationException("Unimplemented method 'addTicket'");
                                                                }
                                                                                                                public void completeTicket(String string, int i) {
                                                                                                                    
                                                                                                                    throw new UnsupportedOperationException("Unimplemented method 'completeTicket'");
                                                                                                                }
                                                                                                                                                                                                                public void completeTicekt(
                                                                                                                                                                                                                        String string,
                                                                                                                                                                                                                        int i) {
                                                                                                                                                                                                                   
                                                                                                                                                                                                                    throw new UnsupportedOperationException("Unimplemented method 'completeTicekt'");
                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                public char[] getCompletedTicketsTotalPoint() {
                                                                                                                                                                                                                                                                                                                                                                                                                                    // TODO Auto-generated method stub
                                                                                                                                                                                                                                                                                                                                                                                                                                    throw new UnsupportedOperationException("Unimplemented method 'getCompletedTicketsTotalPoint'");
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                    int getCompletedTicketsTotalPoint(){
                                                                                                                                                                                                                                                                                                                                                                                                                           int totalPoints=0;
                                                                                                                                                                                                                                                                                                                                                                                                                           for (Ticket ticket:tickets){
                                                                                                                                                                                                                                                                                                                                                                                                                              if(ticket!=null&&ticket.isCompleted){
                                                                                                                                                                                                                                                                                                                                                                                                                                totalPoints+=ticket.point;
                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                       return totalPoints;
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                void addEmployee(Employee e,int pos){
                                                                                                                                                                                                                                                                                                                                                                                                                   if(pos==1){
                                                                                                                                                                                                                                                                                                                                                                                                                    Employee emp1 = e;
                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                   else if(pos==2){
                                                                                                                                                                                                                                                                                                                                                                                                                    Employee emp2 = e;
                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                   else{
                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("invalid things");
                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                void addTicket(Ticket t,int pos){
                                                                                                                                                                                                                                                                                                                                                                                                                    if (pos >= 1 && pos <= 5) {
                                                                                                                                                                                                                                                                                                                                                                                                                        Employee.Ticket[] tickets;
                                                                                                                                                                                                                                                                                                                                                                                                                                tickets[pos - 1] = t;
                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Invalid ticket position. Use 1 to 5.");
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                public class DesignClass {
                                                                                                                                                                                                                                                                                                                                                                                                                    public static void main(String[] args) {
                                                                                                                                                                                                                                                                                                                                                                                                                        HelpDesk helpDesk=new HelpDesk();
                                                                                                                                                                                                                                                                                                                                                                                                        Employee alice=new Employee("aliceBrown",5,Category.SOFTWARE);
                                                                                                                                                                                                                                                                                                                                                                                                        Employee bob= new Employee("Bob Smith",8,Category.HARDWARE);
                                                                                                                                                                                                                                                                                                                                                                                                        helpDesk.addEmployee(alice,1);
                                                                                                                                                                                                                                                                                                                                                                                                helpDesk.addEmployee(bob,2);
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                Ticket t1=new Ticket(101,"SoftwareBug",Category.SOFTWARE,4, "alice",false);
                                                                                                                                                                                                                                                                                                                                                                                                Ticket t2= new Ticket(102,"network Issue",Category.HARDWARE,7, "Bob Smith",true);
                                                                                                                                                                                                                                                                                                                                                                                                Ticket t3= new Ticket(103,"system Crash",Category.HARDWARE,10,"MAnit",true);
                                                                                                                                                                                                                                                                                                                                                                                                Ticket t4= new Ticket(104,"printer Not Working",Category.HARDWARE,3,"miSHRA",false);
                                                                                                                                                                                                                                                                                                                                                                                                Ticket t5= new Ticket(105,"ul Bug",Category.SOFTWARE,2,"KUMAR",true);
                                                                                                                                                                                                                                                                                                                                                                                                helpDesk.addTicket(t1,1);
                                                                                                                                                                                                                                                                                                                                                                                                helpDesk.addTicket(t2,2);
                                                                                                                                                                                                                                                                                                                                                                                                helpDesk.addTicket(t3,3);
                                                                                                                                                                                                                                                                                                                                                                                                helpDesk.addTicket(t4,4);
                                                                                                                                                                                                                                                                                                                                                                                                helpDesk.addTicket(t5,5);
                                                                                                                                                                                                                                                                                                                                                                            helpDesk.completeTicket("Alice Brown",101);
                                                                                                                                                                                                                                                                                                                                                                            helpDesk.completeTicekt("BobSmith",102);
                                                                                                                                                                                                                                                                                                                                                                            helpDesk.completeTicket("Alice Brown",103);
                                                                                                                                                                                                                                                                                                                                                                            helpDesk.completeTicket("bob SMith",104);
                                                                                                                                                                                                                                                                                                                                                                            helpDesk.completeTicekt("ALice BRown",105);
                                                                                                                                                                                                                                                                                                                                                                            System.out.println(helpDesk.getWaitingTicketCount());
                                                                                                                                                                                                                                                                                                                                                                            System.out.println(helpDesk.getCompletedTicketsTotalPoint());


        
    }
}
